feat: Make Service Network Connection optional
GoogleCloudPlatform/terraform-google-cloud-ids pull request #40
Opened 2024-05-30 12:36 UTC by legal90

Fixes https://github.com/GoogleCloudPlatform/terraform-google-cloud-ids/issues/16

This PR adds a new optional variable `create_service_networking_connection` allowing to skip the creation of `servicenetworking` connection and IP range for it.

That is needed when Cloud IDS endpoint is provisioned in the VPC network where `servicenetworking` connection already exists.

The change is backward compatible.

2024-08-01 11:08 UTC, legal90 commented
@apeabody Hi! Could you please review this PR?

2024-08-01 16:15 UTC, apeabody commented
/gcbrun

2024-08-01 16:17 UTC, apeabody requested changes
Thanks for the contribution @legal90!

From lint test:
```
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=autogen' '--exclude=*.tfvars' '--exclude=*metadata.yaml' /workspace/README.md /tmp/tmp.v14MySgbnV/generate_docs/workspace/README.md
44a45
> | create\_service\_networking\_connection | Whether to create service networking connection and IP range. | `bool` | `true` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
```

2024-08-02 16:25 UTC, legal90 commented
@apeabody Thank you! It should be fixed now.

2024-08-02 16:30 UTC, apeabody commented
/gcbrun

2024-08-05 18:19 UTC, apeabody approved these changes
Thanks for the contribution @legal90!

2024-08-05 18:19 UTC, merged